// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hit_and_run_cpp
arma::vec hit_and_run_cpp(const arma::mat& A, const arma::vec& z, const arma::vec& greater_equal, arma::vec x0, int n_iter, const arma::vec& kappa, double rho, std::string kernel, int max_dir_tries, double bound_truncation);
RcppExport SEXP _combreg_hit_and_run_cpp(SEXP ASEXP, SEXP zSEXP, SEXP greater_equalSEXP, SEXP x0SEXP, SEXP n_iterSEXP, SEXP kappaSEXP, SEXP rhoSEXP, SEXP kernelSEXP, SEXP max_dir_triesSEXP, SEXP bound_truncationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type greater_equal(greater_equalSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< int >::type max_dir_tries(max_dir_triesSEXP);
    Rcpp::traits::input_parameter< double >::type bound_truncation(bound_truncationSEXP);
    rcpp_result_gen = Rcpp::wrap(hit_and_run_cpp(A, z, greater_equal, x0, n_iter, kappa, rho, kernel, max_dir_tries, bound_truncation));
    return rcpp_result_gen;
END_RCPP
}
// loop_hit_and_run_cpp
arma::mat loop_hit_and_run_cpp(const arma::mat& A, const arma::mat& Z, const arma::mat& Greater_equal, const arma::mat& X0, const arma::mat& Kappa, int n_iter, double rho, std::string kernel, int max_dir_tries, double bound_truncation, int n_threads);
RcppExport SEXP _combreg_loop_hit_and_run_cpp(SEXP ASEXP, SEXP ZSEXP, SEXP Greater_equalSEXP, SEXP X0SEXP, SEXP KappaSEXP, SEXP n_iterSEXP, SEXP rhoSEXP, SEXP kernelSEXP, SEXP max_dir_triesSEXP, SEXP bound_truncationSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Greater_equal(Greater_equalSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Kappa(KappaSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< int >::type max_dir_tries(max_dir_triesSEXP);
    Rcpp::traits::input_parameter< double >::type bound_truncation(bound_truncationSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(loop_hit_and_run_cpp(A, Z, Greater_equal, X0, Kappa, n_iter, rho, kernel, max_dir_tries, bound_truncation, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// check_feasible_dual_cpp
Rcpp::IntegerVector check_feasible_dual_cpp(const arma::mat& A, const arma::mat& Z, const arma::mat& Greater_equal, const arma::mat& X0, int n_threads);
RcppExport SEXP _combreg_check_feasible_dual_cpp(SEXP ASEXP, SEXP ZSEXP, SEXP Greater_equalSEXP, SEXP X0SEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Greater_equal(Greater_equalSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(check_feasible_dual_cpp(A, Z, Greater_equal, X0, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// check_tum_cpp
List check_tum_cpp(arma::imat M);
RcppExport SEXP _combreg_check_tum_cpp(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(check_tum_cpp(M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_combreg_hit_and_run_cpp", (DL_FUNC) &_combreg_hit_and_run_cpp, 10},
    {"_combreg_loop_hit_and_run_cpp", (DL_FUNC) &_combreg_loop_hit_and_run_cpp, 11},
    {"_combreg_check_feasible_dual_cpp", (DL_FUNC) &_combreg_check_feasible_dual_cpp, 5},
    {"_combreg_check_tum_cpp", (DL_FUNC) &_combreg_check_tum_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_combreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
