# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hit_and_run_cpp <- function(A, z, greater_equal, x0, n_iter, kappa, rho = 1.0, kernel = "exponential", max_dir_tries = 1000L, bound_truncation = 1e5) {
    .Call(`_combreg_hit_and_run_cpp`, A, z, greater_equal, x0, n_iter, kappa, rho, kernel, max_dir_tries, bound_truncation)
}

loop_hit_and_run_cpp <- function(A, Z, Greater_equal, X0, Kappa, n_iter, rho = 1.0, kernel = "exponential", max_dir_tries = 1000L, bound_truncation = 1e5, n_threads = 1L) {
    .Call(`_combreg_loop_hit_and_run_cpp`, A, Z, Greater_equal, X0, Kappa, n_iter, rho, kernel, max_dir_tries, bound_truncation, n_threads)
}

check_feasible_dual_cpp <- function(A, Z, Greater_equal, X0, n_threads = 1L) {
    .Call(`_combreg_check_feasible_dual_cpp`, A, Z, Greater_equal, X0, n_threads)
}

check_tum_cpp <- function(M) {
    .Call(`_combreg_check_tum_cpp`, M)
}

